{% set CONDA_PY = os.environ.get('CONDA_PY', '37') %}
name: uqpy-py{{ CONDA_PY }}

dependencies:
  - fire
  - matplotlib
  - numpy
  - python
  - scikit-learn
  - scipy

environment:
  PYTHONPATH:
    - {{ root }}
  GIBBS_NOTEBOOKS_DIR: {{ root }}/notebooks
  PY_VERSION: {{ CONDA_PY }}