{% set CONDA_PY = os.environ.get('CONDA_PY', '37') %}
name: uqpy-py{{ CONDA_PY }}

dependencies:
  - fire
  - matplotlib
  - numpy
  - python
  - scikit-learn
  - scipy

  # Notebook's dependencies
  - notebook
  - ipywidgets
  - widgetsnbextension
  - jupyter_contrib_nbextensions
  - jupyter_conda

environment:
  PYTHONPATH:
    - {{ root }}
  PY_VERSION: {{ CONDA_PY }}